# Spring Boot Server Port
server.port=8080

# Database Configuration (Cloud MySQL - Aiven)
# UPDATE: ssl-mode=REQUIRED ko badal kar useSSL=true aur trustServerCertificate=true kiya hai, aur Dialect add kiya hai
spring.datasource.url=jdbc:mysql://mysql-28c2238f-hritikarun1234-4eb5.l.aivencloud.com:17799/defaultdb?useSSL=true&trustServerCertificate=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# UPDATE: Forcefully Hibernate ko bata rhe hain ki database MySQL hai
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable detailed error messages in JSON responses
server.error.include-message=always
server.error.include-binding-errors=always

# JWT Configuration
app.jwt.secret=9a67a86c75f3a09e0231db62184d0b135b3401ef942289cf29188a1b52a1d0f5
app.jwt.expiration-ms=86400000